# Generated by Django 5.2.4 on 2025-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
